version: '3.4'

services:
  sqldata:
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "5433:1433"
    networks:
      - demo
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always

  unit-api:
    container_name: unit-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:SqlConnection=Server=mssql;Database=Microservices.Demo.UnitDb;User Id=sa;Password=P@ssw0rd;
      - IdentityServerUrl=http://identityserver
    ports:
      - "5001:80"
    networks:
      - demo
    depends_on:
      - mssql
      - identityserver

  employee-api:
    container_name: employee-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:SqlConnection=Server=mssql;Database=Microservices.Demo.EmployeeDb;User Id=sa;Password=P@ssw0rd;
      - IdentityServerUrl=http://identityserver
    ports:
      - "5002:80"
    networks:
      - demo
    depends_on:
      - mssql
      - identityserver

  aggregator:
    container_name: aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver
    ports:
      - "5003:80"
    networks:
      - demo
    depends_on:
      - identityserver
      - unit-api
      - employee-api

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://identityserver
    ports:
      - "5000:80"
    networks:
      - demo
    depends_on:
      - identityserver
      - unit-api
      - employee-api
      - aggregator

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WebAppSettings:RedirectUrl=http://localhost:8080/signin-oidc
      - WebAppSettings:PostLogoutRedirectUrl=http://localhost:8080/signout-callback-oidc
    ports:
      - "5005:80"
    networks:
      - demo

  webapp:
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerUrl=http://localhost:5005
      - OcelotApiGw=http://ocelotapigw
    ports:
      - "8080:80"
    networks:
      - demo
    extra_hosts:
      - localhost:10.88.0.1
    depends_on:
      - ocelotapigw
      - identityserver
